version: '3.1'

services:

    db:
        restart: unless-stopped
        image: docker.io/library/postgres:15
        container_name: ffksk_dev_database
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 9432:5432
        volumes:
            - ffksk_pg_data:/var/lib/postgresql/data/

volumes:
    ffksk_pg_data:
