version: '3.1'

services:

    db:
        restart: unless-stopped
        image: docker.io/library/postgres:16
        container_name: ffksk_dev_database
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ffksk_pg_data:/var/lib/postgresql/data/
        networks:
            - backend_network

    backend:
        restart: unless-stopped
        build:
            context: ./
            dockerfile: Dockerfile
            target: develop
            args:
                DO_MIGRATE: ${DO_MIGRATE}
                DEBUG_BUILD: ${DEBUG_BUILD}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_DB: ${POSTGRES_DB}
                POSTGRES_HOST: ${POSTGRES_HOST}
                POSTGRES_PORT: ${POSTGRES_PORT}
        command: bash -c "if [ "$DEBUG_BUILD" = "true" ] ; then python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:3002 ; else python manage.py runserver 0.0.0.0:3002 ; fi"
        container_name: ffksk_dev_backend
        image: backend_dev
        ports:
            - 3002:3002
            - 5678:5678
        depends_on:
            - db
        volumes:
            - ./:/ffksk
        networks:
            - backend_network

volumes:
    ffksk_pg_data:

networks:
  backend_network:
