from django.urls import re_path
from . import views, slackCommands, slackMessages

urlpatterns = [
	re_path(r'^$', views.start_page, name='start_page'),
	re_path(r'^imkiosk/$', views.imkiosk_page, name='imkiosk_page'),	
	re_path(r'^offeneEkListe/$', views.offeneEkListe_page, name='offeneEkListe_page'),
	re_path(r'^impressum/$', views.impressum_page, name='impressum_page'),
	re_path(r'^kontakt/$', views.kontakt_page, name='kontakt_page'),
	re_path(r'^datenschutzerklaerung/$', views.datenschutz_page, name='datenschutz_page'),
	re_path(r'^menu/$', views.home_page, name='home_page'),
	re_path(r'^menu/kauf/$', views.kauf_page, name='kauf_page'),
	re_path(r'^menu/gekauft/$', views.gekauft_page, name='gekauft_page'),
	re_path(r'^menu/kaufabgelehnt/$', views.kauf_abgelehnt_page, name='kauf_abgelehnt_page'),
	re_path(r'^menu/kontobewegungen/$', views.kontobewegungen_page, name='kontobewegungen_page'),
	re_path(r'^menu/kontobewegungen/(?P<s>\d+)/$', views.kontobewegungen_page_next, name='kontobewegungen_page_next'),
	re_path(r'^menu/einkaufsvormerkungen/$', views.einkauf_vormerk_page, name = 'einkauf_vormerk_page'),
	re_path(r'^menu/einkaufsannahme/$', views.einkauf_annahme_page, name = 'einkauf_annahme_page'),
	re_path(r'^menu/einkaufsannahme/(?P<userID>\d+)/$', views.einkauf_annahme_user_page, name='einkauf_annahme_user_page'),
	re_path(r'^menu/transaktion/$', views.transaktion_page, name = 'transaktion_page'),
	re_path(r'^menu/neuerNutzer/$', views.neuerNutzer_page, name = 'neuerNutzer_page'),
	re_path(r'^menu/einzahlung/$', views.einzahlung_page, name = 'einzahlung_page'),
	re_path(r'^menu/meineeinkaufe/$', views.meine_einkaufe_page, name = 'meine_einkaufe_page'),
	re_path(r'^menu/fillKioskUp/$', views.fillKioskUp, name = 'fillKioskUp'),
	re_path(r'^menu/inventory/$', views.inventory, name = 'inventory'),
	re_path(r'^menu/inventory/done/$', views.inventory_done, name = 'inventory_done'),
	re_path(r'^menu/statistics/$', views.statistics, name = 'statistics'),
	re_path(r'^menu/produktKommentare/$', views.produktKommentare, name = 'produkt_kommentare_page'),
	re_path(r'^menu/produktKommentieren/(?P<s>\d+)/$', views.produktKommentieren, name='produkt_kommentieren_page'),
	re_path(r'^menu/infos/$', views.anleitung, name = 'anleitung_page'),
	re_path(r'^menu/ersteSchritte/$', views.ersteSchritte, name = 'ersteschritte_page'),
	re_path(r'^menu/regelwerk/$', views.regelwerk, name = 'regelwerk_page'),
	re_path(r'^menu/rueckbuchung/$', views.rueckbuchung, name = 'rueckbuchungen_page'),
	re_path(r'^menu/rueckbuchung/(?P<userID>\d+)/$', views.rueckbuchung_user, name = 'rueckbuchungen_user_page'),
	re_path(r'^menu/slackComTest/$', views.slackComTest, name = 'slackComTest_page'),

	re_path(r'^receiveSlackCommands/$', slackCommands.receiveSlackCommands, name = 'receiveSlackCommands'),
	re_path(r'^receiveSlackMessages/$', slackMessages.receiveSlackMessages, name = 'receiveSlackMessages'),
	
]