# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 15:46
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskuser',
            name='positionFfE',
            field=models.CharField(blank=True, choices=[('WiHi', 'Student'), ('MA', 'Festangestellter')], max_length=15),
        ),
        migrations.AlterField(
            model_name='kioskuser',
            name='rechte',
            field=models.CharField(choices=[('User', 'Standardnutzer'), ('Buyer', 'Einkäufer'), ('Accountant', 'Verwalter'), ('Admin', 'Admin')], default='User', max_length=15),
        ),
        migrations.AlterField(
            model_name='kioskuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
