# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20171119_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kioskuser',
            options={'permissions': (('do_admin_tasks', 'Einpflegen von Usern, Geldtransaktionen, ...'), ('do_verwaltung', 'Einarbeiten von Waren ins Kiosk'), ('do_einkauf', 'Einkäufe vormerken und einkaufen'), ('perm_kauf', 'Kaufen im Kiosk'))},
        ),
        migrations.AlterField(
            model_name='kioskuser',
            name='aktivBis',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kioskuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Mail-Adresse'),
        ),
    ]
