# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import profil.models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20180304_2051'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kioskuser',
            managers=[
                ('objects', profil.models.KioskUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='kioskuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
