# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_auto_20180328_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
