# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_auto_20180328_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskuser',
            name='activity_end_msg',
            field=models.IntegerField(default=0),
        ),
    ]
