# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_auto_20180618_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskuser',
            name='slackName',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
