# Generated by Django 5.0.7 on 2024-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_auto_20191219_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskuser',
            name='paypal_name',
            field=models.CharField(default='empty', help_text='Name, der bei PayPal nach außen zu sehen ist', max_length=64,),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kioskuser',
            name='activity_end_msg',
            field=models.IntegerField(default=0, help_text='0: Active, nothing sent. 1: Active, message sent that in 7 days, account will be blocked. 2: Inactive, invisible, Inactivity message sent. 3: Account is now unpersonalised, money is donated to Kiosk'),
        ),
        migrations.AlterField(
            model_name='kioskuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='kioskuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='kioskuser',
            name='slackName',
            field=models.CharField(help_text='Slack ID oder Name hinter @, falls keine Leerzeichen oder Umlaute.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='kioskuser',
            name='visible',
            field=models.BooleanField(default=True, help_text='Bank, Dieb, usw. sollen nicht gesehn und nicht angewaehlt werden duerfen, z.B. bei Einkauf-Annahme'),
        ),
    ]
