# Generated by Django 5.0.7 on 2024-07-19 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0012_alter_kioskuser_aktivbis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskuser',
            name='aktivBis',
            field=models.DateField(default=datetime.date(2024, 7, 19)),
        ),
    ]
