# Generated by Django 5.0.7 on 2024-07-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0015_alter_kioskuser_aktivbis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskuser',
            name='paypal_name',
            field=models.CharField(blank=True, help_text='Name, der bei PayPal nach außen zu sehen ist', max_length=64, null=True),
        ),
    ]
