# Generated by Django 5.0.7 on 2024-07-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0016_alter_kioskuser_paypal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kioskuser',
            name='email',
        ),
    ]
