# Generated by Django 5.0.7 on 2024-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0017_remove_kioskuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskuser',
            name='is_functional_user',
            field=models.BooleanField(default=False, help_text='Set to true, if this is no real user, but System user'),
        ),
    ]
