# Generated by Django 5.0.7 on 2024-08-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0018_kioskuser_is_functional_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
