# Generated by Django 5.0.7 on 2024-08-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0019_alter_kioskuser_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kioskuser',
            options={'default_manager_name': 'objects', 'permissions': (('do_admin_tasks', 'Einpflegen von Usern, Geldtransaktionen, ...'), ('do_verwaltung', 'Einarbeiten von Waren ins Kiosk'), ('do_einkauf', 'Einkäufe vormerken und einkaufen'), ('perm_kauf', 'Kaufen im Kiosk'))},
        ),
    ]
