# Generated by Django 5.1.7 on 2025-05-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0020_alter_kioskuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kioskuser',
            options={'default_manager_name': 'objects', 'permissions': (('do_admin_tasks', 'Kontaktnachrichten, Statistiken, Erweiterte Produktverwaltung, Nutzerverwaltung'), ('do_verwaltung_product_operations', 'Besorgungen annehmen, Einkäufe rückbuchen, Inventur durchführen'), ('do_verwaltung_financial_operations', 'Einzahlungen, Auszahlungen und Geldtransaktionen abwickeln'), ('do_verwaltung_product_management', 'Produktlisten und -preise pflegen'), ('do_einkauf', 'Produkte vormerken und besorgen'), ('perm_kauf', 'Einkaufen im Kiosk'))},
        ),
    ]
