# Generated by Django 5.1.7 on 2025-05-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0021_alter_kioskuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kioskuser',
            name='rechte',
        ),
    ]
