# Generated by Django 5.0.7 on 2024-07-19 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kiosk', '0011_alter_einkaufsliste_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(help_text='ID from Outlook', unique=True)),
                ('envelope_str', models.TextField(help_text='Envelope string from Outlook', unique=True)),
                ('data', models.TextField(help_text='Mail data')),
                ('extraction_was_successful', models.BooleanField(help_text='Mail extraction was successful, if all values could be extracted')),
                ('assignment_was_successful', models.BooleanField(help_text='Mail assignment to a user was successful')),
                ('user_str', models.CharField(blank=True, help_text='Extracted user', max_length=64, null=True)),
                ('transaction_code', models.CharField(blank=True, help_text='Extracted transaction code', max_length=64, null=True)),
                ('transaction_date', models.DateField(blank=True, help_text='Extracted transaction date', null=True)),
                ('amount', models.IntegerField(blank=True, help_text='Extracted amount sent', null=True)),
                ('geld_transaktion', models.OneToOneField(blank=True, help_text='transaction of "Einzahlung" that has been created from this mail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_geld_transaktion', to='kiosk.geldtransaktionen')),
                ('user', models.ForeignKey(blank=True, help_text='Assignment based on user_str and paypal_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Mails',
            },
        ),
    ]
