# Generated by Django 5.0.7 on 2024-07-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='assignment_was_successful',
            field=models.BooleanField(default=False, help_text='Mail assignment to a user was successful'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='extraction_was_successful',
            field=models.BooleanField(default=False, help_text='Mail extraction was successful, if all values could be extracted'),
        ),
    ]
