# Generated by Django 5.0.7 on 2024-07-19 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0002_alter_mail_assignment_was_successful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_ts',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Mail received (envelope)'),
            preserve_default=False,
        ),
    ]
