# Generated by Django 5.0.7 on 2024-07-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0003_mail_mail_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='notice',
            field=models.TextField(blank=True, help_text='Extracted notice text', null=True),
        ),
    ]
