# Generated by Django 5.1 on 2024-08-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0004_mail_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='transaction_date',
        ),
    ]
