# Generated by Django 5.1 on 2024-12-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0005_remove_mail_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_is_processed',
            field=models.BooleanField(default=False, help_text='Mail has been read and necessary action was taken.'),
        ),
    ]
