# Generated by Django 5.2.3 on 2025-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0007_alter_mail_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Token to access Gmail')),
            ],
            options={
                'verbose_name': 'GMail Token',
                'verbose_name_plural': 'GMail Tokens',
            },
        ),
    ]
