# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 13:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einkaufsliste',
            fields=[
                ('kiosk_ID', models.AutoField(primary_key=True, serialize=False)),
                ('bedarfErstelltUm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EinkaufslisteGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppenID', models.IntegerField()),
                ('einkaufslistenItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Einkaufsliste')),
            ],
        ),
        migrations.CreateModel(
            name='Gekauft',
            fields=[
                ('kiosk_ID', models.AutoField(primary_key=True, serialize=False)),
                ('bedarfErstelltUm', models.DateTimeField()),
                ('einkaufsvermerkUm', models.DateTimeField()),
                ('geliefertUm', models.DateTimeField()),
                ('einkaufspreis', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('gekauftUm', models.DateTimeField(auto_now_add=True)),
                ('verkaufspreis', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='GeldTransaktionen',
            fields=[
                ('AutoTrans_ID', models.AutoField(primary_key=True, serialize=False)),
                ('betrag', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('kommentar', models.TextField(blank=True, max_length=512)),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('kiosk_ID', models.AutoField(primary_key=True, serialize=False)),
                ('bedarfErstelltUm', models.DateTimeField()),
                ('einkaufsvermerkUm', models.DateTimeField()),
                ('geliefertUm', models.DateTimeField(auto_now_add=True)),
                ('einkaufspreis', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Kontostand',
            fields=[
                ('nutzer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produktpalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produktName', models.CharField(max_length=40)),
                ('produktErstellt', models.DateTimeField(auto_now_add=True)),
                ('produktGeaendert', models.DateTimeField(auto_now=True)),
                ('kommentar', models.TextField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ProduktVerkaufspreise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verkaufspreis', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('gueltigAb', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ZumEinkaufVorgemerkt',
            fields=[
                ('kiosk_ID', models.AutoField(primary_key=True, serialize=False)),
                ('bedarfErstelltUm', models.DateTimeField()),
                ('einkaufsvermerkUm', models.DateTimeField(auto_now_add=True)),
                ('einkaeufer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZuVielBezahlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('preis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kioskkapazitaet',
            fields=[
                ('produktpalette', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kiosk.Produktpalette')),
                ('maxKapazitaet', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('schwelleMeldung', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('paketgroesseInListe', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='zuvielbezahlt',
            name='produkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Produktpalette'),
        ),
        migrations.AddField(
            model_name='zumeinkaufvorgemerkt',
            name='produktpalette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Produktpalette'),
        ),
        migrations.AddField(
            model_name='produktverkaufspreise',
            name='produktpalette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Produktpalette'),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='einkaeufer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_einkaeufer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='produktpalette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Produktpalette'),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='verwalterEinpflegen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_verwalter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geldtransaktionen',
            name='vonnutzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutzerVon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geldtransaktionen',
            name='zunutzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutzerZu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gekauft',
            name='einkaeufer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gekauft_einkaeufer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gekauft',
            name='kaeufer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gekauft_kaeufer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gekauft',
            name='produktpalette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Produktpalette'),
        ),
        migrations.AddField(
            model_name='gekauft',
            name='verwalterEinpflegen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gekauft_verwalter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='einkaufsliste',
            name='produktpalette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Produktpalette'),
        ),
    ]
