# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zuvielbezahlt',
            name='produkt',
        ),
        migrations.DeleteModel(
            name='ZuVielBezahlt',
        ),
    ]
