# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20170920_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZuVielBezahlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('preis', models.IntegerField()),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Produktpalette')),
            ],
        ),
    ]
