# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_auto_20170930_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produktpalette',
            name='kommentar',
        ),
    ]
