# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_produktpalette_imverkauf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt_Nachricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('gesendet', models.DateTimeField(auto_now_add=True)),
                ('betreff', models.TextField(blank=True, max_length=128)),
                ('text', models.TextField(max_length=1024)),
                ('beantwortet', models.BooleanField(default=False)),
            ],
        ),
    ]
