# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_start_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekauft',
            name='gekauft_per',
            field=models.CharField(choices=[('slack', 'slack'), ('web', 'web'), ('ubk', 'unbekannt'), ('dieb', 'dieb')], default='ubk', max_length=6),
        ),
    ]
