# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 20:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0009_gekauft_gekauft_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='produktpalette',
            name='inAufstockung',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produktverkaufspreise',
            name='preisAufstockung',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
