# Generated by Django 5.0.7 on 2024-08-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0012_alter_einkaufslistegroups_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produktpalette',
            name='produktName',
            field=models.CharField(max_length=64),
        ),
    ]
