# Generated by Django 5.1.7 on 2025-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0013_alter_produktpalette_produktname'),
    ]

    operations = [
        migrations.AddField(
            model_name='produktpalette',
            name='is_beverage',
            field=models.BooleanField(default=False, help_text='Set to True if the product comes with pledge (Pfand)'),
        ),
    ]
