# Generated by Django 5.1.7 on 2025-05-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0014_produktpalette_is_beverage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Start_News',
        ),
    ]
