# Generated by Django 5.1.7 on 2025-05-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0015_delete_start_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produktpalette',
            name='farbeFuerPlot',
        ),
    ]
