# Generated by Django 5.1.7 on 2025-05-19 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0016_remove_produktpalette_farbefuerplot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='geldtransaktionen',
            name='user_conducted',
            field=models.ForeignKey(blank=True, help_text='User who conducted the transaction. If not set, it is assumed that the transaction was conducted by the system (e.g. automatic transactions).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
